export const apiEndpoints = {
  items: {
    list: "/api/v1/items",
    create: "/api/v1/items",
    byId: (itemId: string) => `/api/v1/items/${itemId}`,
    restore: (itemId: string) => `/api/v1/items/${itemId}/restore`,
  },
  categories: {
    list: "/api/v1/categories",
  },
  brands: {
    search: "/api/v1/brands/search",
  },
  uploads: "/api/v1/uploads",
  auth: {
    register: "/api/v1/auth/register",
    googleStart: "/api/v1/auth/google/auth",
    googleCallback: "/api/v1/auth/google/callback",
    login: "/api/v1/auth/login",
    me: "/api/v1/auth/me",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
  },
  adminUsers: {
    list: "/api/v1/admin/users",
    create: "/api/v1/admin/users",
    byEmail: "/api/v1/admin/users/by-email",
    byId: (userId: string) => `/api/v1/admin/users/${userId}`,
    activate: (userId: string) => `/api/v1/admin/users/${userId}/activate`,
    deactivate: (userId: string) => `/api/v1/admin/users/${userId}/deactivate`,
  },
  cart: {
    root: "/api/v1/cart",
    items: "/api/v1/cart/items",
    item: (itemId: string) => `/api/v1/cart/items/${itemId}`,
    select: (itemId: string) => `/api/v1/cart/items/${itemId}/select`,
  },
  taxRate: "/api/v1/admin/settings/tax-rate",
  profile: {
    root: "/api/v1/customer-profile",
    addresses: "/api/v1/customer-profile/addresses",
    address: (addressId: string) => `/api/v1/customer-profile/addresses/${addressId}`,
    email: "/api/v1/customer-profile/update-email",
    password: "/api/v1/customer-profile/update-password",
  },
  orders: {
    checkoutCart: "/api/v1/orders/checkout/cart",
    directPreview: "/api/v1/orders/checkout/direct/preview",
    direct: "/api/v1/orders/checkout/direct",
    list: "/api/v1/orders",
    history: "/api/v1/orders/history/items",
    byId: (orderId: string) => `/api/v1/orders/${orderId}`,
    bill: (orderId: string) => `/api/v1/orders/${orderId}/bill`,
  },
  adminOrders: {
    list: "/api/v1/admin/orders",
    search: "/api/v1/admin/orders/search",
    byId: (orderId: string) => `/api/v1/admin/orders/${orderId}`,
    status: (orderId: string) => `/api/v1/admin/orders/${orderId}/status`,
  },
} as const;
