import { Boxes, PackageCheck, ShoppingCart, TriangleAlert, UserRoundCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { OrderStatusBadge } from "@/components/ui/status-badge";
import { formatLkr } from "@/lib/formatting/currency";
import { mockOrders } from "@/mocks/data";

const metrics = [{ label: "Total items", value: "248", note: "232 active", icon: Boxes }, { label: "Orders", value: "1,284", note: "38 this month", icon: ShoppingCart }, { label: "Pending orders", value: "14", note: "Needs review", icon: PackageCheck }, { label: "Customers", value: "3,842", note: "112 new", icon: UsersRound }, { label: "Active customers", value: "3,706", note: "96.5% active", icon: UserRoundCheck }, { label: "Low-stock", value: "8", note: "Placeholder", icon: TriangleAlert }];
export default function AdminDashboardPage() { return <div><AdminPageHeader title="Good afternoon, Kasun" description="Here is the current storefront snapshot. Metrics use development mock data until dashboard endpoints are confirmed." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(({ label, value, note, icon: Icon }) => <article className="panel p-5" key={label}><div className="flex items-start justify-between"><span className="flex size-11 items-center justify-center rounded-2xl bg-soft/50 text-brand"><Icon className="size-5" /></span><span className="rounded-full bg-surface-muted px-2.5 py-1 text-[10px] font-black text-ink-muted">Mock</span></div><p className="mt-5 text-sm font-bold text-ink-muted">{label}</p><p className="mt-1 text-3xl font-black text-brand">{value}</p><p className="mt-2 text-xs text-ink-muted">{note}</p></article>)}</div><section className="panel mt-6 overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-border p-5"><div><h2 className="text-lg font-black text-brand">Recent orders</h2><p className="mt-1 text-xs text-ink-muted">Latest customer activity</p></div><Link href="/admin/orders" className="text-xs font-black text-brand hover:underline">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-surface-muted text-xs text-ink-muted"><tr><th className="px-5 py-3 font-bold">Order</th><th className="px-5 py-3 font-bold">Customer</th><th className="px-5 py-3 font-bold">Date</th><th className="px-5 py-3 font-bold">Status</th><th className="px-5 py-3 text-right font-bold">Total</th></tr></thead><tbody>{mockOrders.map((order,index) => <tr className="border-t border-border" key={order.id}><td className="px-5 py-4 font-black text-brand">{order.id}</td><td className="px-5 py-4">{["Ayesha Perera","Nimal Silva","Fathima Rizvi"][index]}</td><td className="px-5 py-4 text-ink-muted">{order.date}</td><td className="px-5 py-4"><OrderStatusBadge status={order.status} /></td><td className="px-5 py-4 text-right font-black text-brand">{formatLkr(order.total)}</td></tr>)}</tbody></table></div></section></div>; }
